/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package iuswing;

import Dominio.Exceptions.UsuarioException;
import Dominio.Fachada;
import Dominio.Mesa;
import Dominio.Usuario.Jugador;
import Dominio.Usuario.Usuario;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import ui.controller.InicioJugadorController;
import ui.view.InicioJugadorView;
/**
 *
 * @author HOLA
 */
public class inicioJugador extends javax.swing.JDialog implements InicioJugadorView {

    private java.awt.Frame padre;
    private InicioJugadorController controller;


    public inicioJugador(java.awt.Frame parent, boolean modal,Jugador jugador ) {
        
        super(parent, modal);
        initComponents();
        controller=new InicioJugadorController(this,jugador);
        cargarNombre(jugador);
        cargarSaldo(jugador);
        mostrarMesasCreadas(Fachada.getInstancia().getMesas());//aca como hago para pasarle mesas sin tener fachada?
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datosPrueba1 = new Inicio.DatosPrueba();
        labelSaldo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listMesasAbiertas = new javax.swing.JList<>();
        txtNombreCompleto = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        txtSaldo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelSaldo.setText("Saldo:");

        listMesasAbiertas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMesasAbiertasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listMesasAbiertas);

        btnCerrarSesion.setText("Cerrar sesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreCompleto)
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
      controller.cerrarSesion();
      
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void listMesasAbiertasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMesasAbiertasMouseClicked
        /*int index=listMesasAbiertas.getSelectedIndex();*/
        
        Mesa mesaSeleccionada = (Mesa)listMesasAbiertas.getSelectedValue();
        controller.EntrarAMesa(mesaSeleccionada);
    }//GEN-LAST:event_listMesasAbiertasMouseClicked

   

   
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private Inicio.DatosPrueba datosPrueba1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelSaldo;
    private javax.swing.JList<Object> listMesasAbiertas;
    private javax.swing.JLabel txtNombreCompleto;
    private javax.swing.JLabel txtSaldo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cargarSaldo(Jugador jugador) {
        
      txtSaldo.setText(Double.toString(jugador.getSaldoInicial()));
    }

    private void cargarNombre(Jugador jugador) {
        txtNombreCompleto.setText(jugador.getNombreCompleto());
      
    }

    @Override
    public void cargarSiguientePantalla(Mesa mesaSeleccionada,Jugador jugador) {
      InicioMesa a= new InicioMesa(padre,false,mesaSeleccionada,jugador);
      a.setVisible(true);
    }

    @Override
    public void mostrarMesasCreadas(List<Mesa> mesasCreadas) {
      //  List<String> mesasFormateadas = formatearMesasCreadas(mesasCreadas);
       // String[] listaMesasCreadasArray = new String[mesasFormateadas.size()];
        //listMesasAbiertas.setListData(mesasFormateadas.toArray(listaMesasCreadasArray));
        
         listMesasAbiertas.setListData(mesasCreadas.toArray()); 
        }

     private List<String> formatearMesasCreadas(List<Mesa> mesasCreadas) {
        List<String> mesasFormateadas = new ArrayList<>();
        for (Mesa mesa: mesasCreadas) {
            mesasFormateadas.add(formatearMesasCreadas(mesa));
        }
        return mesasFormateadas;
    }

    private String formatearMesasCreadas(Mesa mesa) {
        return mesa.getNumero()+ "|" +
                mesa.getCantidadJugadores() + "|" +
                mesa.getApuestaBase() + "|"+ mesa.getJugadores().size() + "|"+
                mesa.getManos().size() + "|" + mesa.TotalApostado()+"|"+
                mesa.getPorcentajeComision()+"|"+ mesa.getEstadoMesa();
    }
    
    
    @Override
    public void mostrarMensaje(String msg) {
        JOptionPane.showMessageDialog(this, msg);  
    }
    
    @Override //no se si estao esta bien ahre
     public void salir() {
        int opcion = JOptionPane.showConfirmDialog(this, "Desea Salir?");
        if (opcion == JOptionPane.YES_OPTION) {
            this.setVisible(false);
          
        }
}}