/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package iuswing;
import ui.view.LoginView;
/**
 *
 * @author bsout
 */
import javax.swing.JOptionPane;
import iuswing.InicioAdmin;


public abstract class Login extends javax.swing.JDialog implements LoginView {
 private java.awt.Frame padre;
    /**
     * Creates new form LoginJugador
     */
    public Login(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        padre = parent;
        initComponents();
        limpiarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHacerLogin = new javax.swing.JButton();
        labelNombreLogin = new javax.swing.JLabel();
        labelPasswordLogin = new javax.swing.JLabel();
        txtNombreLogin = new javax.swing.JTextField();
        txtPasswordLogin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnHacerLogin.setText("Login");
        btnHacerLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHacerLoginActionPerformed(evt);
            }
        });

        labelNombreLogin.setText("Nombre Completo:");

        labelPasswordLogin.setText("Password:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNombreLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPasswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHacerLogin)
                            .addComponent(txtPasswordLogin))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombreLogin)
                    .addComponent(txtNombreLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPasswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPasswordLogin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnHacerLogin)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHacerLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHacerLoginActionPerformed
       String user=txtNombreLogin.getText();
       String contra=txtPasswordLogin.getText();
       this.Login(user,contra);
   
    }//GEN-LAST:event_btnHacerLoginActionPerformed

       
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHacerLogin;
    private javax.swing.JLabel labelNombreLogin;
    private javax.swing.JLabel labelPasswordLogin;
    private javax.swing.JTextField txtNombreLogin;
    private javax.swing.JTextField txtPasswordLogin;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
        txtNombreLogin.setText("");
        txtPasswordLogin.setText("");
}
}