/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package iuswing;

import Dominio.Fachada;
import Dominio.Mano;
import Dominio.Mesa;
import java.util.ArrayList;
import java.util.List;
import ui.controller.AgregarManoController;
import ui.view.AgregarManoView;

/**
 *
 * @author HOLA
 */
public class ManosAdmin extends javax.swing.JDialog implements AgregarManoView {
    private Mesa mesa;
    /**
     * Creates new form ManosAdmin
     */
    private AgregarManoController controller;
    public ManosAdmin(java.awt.Frame parent, boolean modal,Mesa m) {
        super(parent, modal);
        initComponents();
        this.mesa=m;
        
        controller= new AgregarManoController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ListManos = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(ListManos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
public void CargarManos(){
   List<Mano> manos=mesa.getManos();
   ListManos.setListData((String[]) manos.toArray());

}

@Override
    public void mostrarManosCreadas() {
        List<Mano> manosCreadas = mesa.getManos();
        List<String> manosFormateadas = formatearManosCreadas(manosCreadas);
        String[] listaManosCreadasArray = new String[manosFormateadas.size()];
        ListManos.setListData(manosFormateadas.toArray(listaManosCreadasArray));
        }
    
      private List<String> formatearManosCreadas(List<Mano> manosCreadas) {
        List<String> manosFormateadas = new ArrayList<>();
        for (Mano mano: manosCreadas) {
            manosFormateadas.add(formatearManosCreadas(mano));
        }
        return manosFormateadas;
    }

    private String formatearManosCreadas(Mano mano) {
        return mano.getNumero()+"|";//+ "|" +mano.getTotalApostado()+"|"+,mano.getEstadoActual()+"|"+mano.getJugadorGanador();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListManos;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

   

    @Override
    public void mostrarMensaje(String msg) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void cargarSiguientePantalla() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
